# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
target 'CHFirim' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CHFirim
pod 'CHBaseUtil', '~> 0.0.5'

pod 'SDWebImage', '~>3.8'
pod 'Alert', '~> 1.0.4'
pod 'UMengAnalytics'
pod 'QRCodeReaderViewController', '~> 4.0.2'
pod 'CHShareUtil', '~> 0.0.5'
pod 'umvideosdk', '~> 4.1.4'
pod 'EAIntroView', '~> 2.10.0'
pod 'WechatOpenSDK'
pod 'RESideMenu', '~> 4.0.7'

end
